<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>CursorPalette</RootNamespace>
		<AssemblyName>Cursor-Palette.Core</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SharpCompress" Version="0.49.1" />
	</ItemGroup>

</Project>
