<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>CursorPalette</RootNamespace>
		<AssemblyName>Cursor-Palette</AssemblyName>
		<Version>1.1.2</Version>
		<InvariantGlobalization>false</InvariantGlobalization>
		<ApplicationIcon>app.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="System.IO" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="app.ico" />
		<Resource Include="Resources\OpenFolder52.png" />
		<Resource Include="Resources\OpenFolder26.png" />
		<Resource Include="Resources\OpenFolder104.png" />
		<Resource Include="Resources\GitHub48.png" />
		<Resource Include="Resources\LinkIcon32.png" />
		<Resource Include="Resources\DefaultCursors\Crosshair.cur" />
		<Resource Include="Resources\DefaultCursors\IBeam.cur" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SharpCompress" Version="0.38.0" />
	</ItemGroup>

</Project>
