<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>CursorPalette</RootNamespace>
		<AssemblyName>Cursor-Palette</AssemblyName>
		<Version>2.0.3</Version>
		<InvariantGlobalization>false</InvariantGlobalization>
		<ApplicationIcon>app.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="System.IO" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="app.ico" />
		<Resource Include="Resources\OpenFolder52.png" />
		<Resource Include="Resources\OpenFolder26.png" />
		<Resource Include="Resources\OpenFolder104.png" />
		<Resource Include="Resources\GitHub48.png" />
		<Resource Include="Resources\LinkIcon32.png" />
		<Resource Include="Resources\LockIcon26.png" />
		<Resource Include="Resources\DownloadIcon32.png" />
		<Resource Include="Resources\OpenFolderIcon32.png" />
		<Resource Include="Resources\ImportIcon26.png" />
		<Resource Include="Resources\GridSquaresIcon32.png" />
		<Resource Include="Resources\ArrowIcon48.png" />
		<Resource Include="Resources\CenterIcon26.png" />
		<Resource Include="Resources\EraseIcon32.png" />
		<Resource Include="Resources\PencilIcon48.png" />
		<Resource Include="Resources\FillIcon32.png" />
		<Resource Include="Resources\EyedropperIcon48.png" />
		<Resource Include="Resources\ImageRefIcon32.png" />
		<Resource Include="Resources\DefaultCursors\Crosshair.cur" />
		<Resource Include="Resources\DefaultCursors\IBeam.cur" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SharpCompress" Version="0.49.1" />
	</ItemGroup>

</Project>
